// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgThDnzNk8qcgjDoky2ryuiZ6PE3oqxM',
    appId: '1:172130531618:web:d30dc9d6efd20fef6a4d7b',
    messagingSenderId: '172130531618',
    projectId: 'test-project-f79c6',
    authDomain: 'test-project-f79c6.firebaseapp.com',
    storageBucket: 'test-project-f79c6.firebasestorage.app',
    measurementId: 'G-C6BCKGZF5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnVR8Om4uiSpnTeHXGvV8wyz8DduGAFs',
    appId: '1:172130531618:android:e14c8817a51579646a4d7b',
    messagingSenderId: '172130531618',
    projectId: 'test-project-f79c6',
    storageBucket: 'test-project-f79c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcNF-bT9jCV6u_FDVfoaXTD9_sc0W--g4',
    appId: '1:172130531618:ios:7bef6bfb6280b7066a4d7b',
    messagingSenderId: '172130531618',
    projectId: 'test-project-f79c6',
    storageBucket: 'test-project-f79c6.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcNF-bT9jCV6u_FDVfoaXTD9_sc0W--g4',
    appId: '1:172130531618:ios:7bef6bfb6280b7066a4d7b',
    messagingSenderId: '172130531618',
    projectId: 'test-project-f79c6',
    storageBucket: 'test-project-f79c6.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfgThDnzNk8qcgjDoky2ryuiZ6PE3oqxM',
    appId: '1:172130531618:web:63d1ef13f7fd43926a4d7b',
    messagingSenderId: '172130531618',
    projectId: 'test-project-f79c6',
    authDomain: 'test-project-f79c6.firebaseapp.com',
    storageBucket: 'test-project-f79c6.firebasestorage.app',
    measurementId: 'G-PFG37SYKMS',
  );
}
